### ISSUE TITLE
GPU decode error

### ISSUE THREAD

**Issue by Mdaughter** [dmlc/decord#145]
I run the code in docker container and its image is pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel.
I follow the example and build successfully, but something wrong happen
```python
from decord import VideoReader
from decord import cpu, gpu
video='/data/Celeb-DF-v2/YouTube-real/00000.mp4'
vr = VideoReader(video, ctx=gpu(0))
frames = vr.get_batch([1, 3, 5, 7, 9])
```
The error pops out like:
```python
CUDA error 3000 at line 341 in file /workspace/decord/src/video/nvcodec/cuda_threaded_decoder.cc: Traceback (most recent call last):
  File "/workspace/decord/python/test.py", line 5, in <module>
    x = vr[1]
  File "/workspace/decord/python/decord/video_reader.py", line 104, in __getitem__
    self.seek_accurate(idx)
  File "/workspace/decord/python/decord/video_reader.py", line 232, in seek_accurate
    success = _CAPI_VideoReaderSeekAccurate(self._handle, pos)
  File "/workspace/decord/python/decord/_ffi/_ctypes/function.py", line 174, in __call__
    check_call(_LIB.DECORDFuncCall(
  File "/workspace/decord/python/decord/_ffi/base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [11:17:09] /workspace/decord/src/video/nvcodec/cuda_threaded_decoder.cc:270: Check failed: run_.load():
```
Env:ffmpeg 4.3.2,cuda 11.0,RTX 2080 Ti,Ubuntu 18.04

**Comment by trifle** [comment]
Hi, I don't have very specific solutions but a few general observations that are always useful:
- Ensure you have an up-to-date version of docker and nvidia-docker
- Ensure your system drivers are new enough to support the version of CUDA you're running
- !! Make sure your system (not docker image) has the required drivers installed, especially nvcuvid - these are not present in the container, they are linked in!
- make sure to expose all gpu capabilities and the correct gpus to the container when running
- make sure there is no version mismatch between the CUDA libraries installed in the container and those required by your python libraries

If in doubt, there's a new Dockerfile in this repo that has been provided by levan92. You can try to use that as a baseline and install torch from within that.

**Comment by sandcobainer** [comment]
I see the same issue with `ctx=cpu(0)`, so I doubt if it's anything to do with the GPU

**Comment by jbohnslav** [comment]
I have the same issue on one of my videos-- CPU only. 

I then tried `vr.next()` and got a more specific error message: 
```
/github/workspace/src/video/ffmpeg/threaded_decoder.cc:292: [12:57:23] /github/workspace/src/video/ffmpeg
/threaded_decoder.cc:218: Check failed: avcodec_send_packet(dec_ctx_.get(), pkt.get()) >= 0 (-22 vs. 0) 
Thread worker: Error sending packet.
```

**Comment by mbanani** [comment]
I am facing a similar bug where the first N frames will be okay, but anything after frame N will result in those errors (sending packets and run_.load(). Did any one figure this out?

I am not sure if it's related to this [issue](https://github.com/ultralytics/yolov5/issues/2064?fbclid=IwAR0-1ekcyFHAkvOoIDjc0Wz-MXeOP1aWeU9TQDuBeatzKuYkXC-jJ5ofIOM#issuecomment-974200888) regarding corrupt frames or pertaining to videos coming from specific cameras.

**Comment by schmidtdominik** [comment]
> I am facing a similar bug where the first N frames will be okay, but anything after frame N will result in those errors

I'm having this exact issue too when decoding on the CPU. It's not related to corrupt files because the problem doesn't occur if I install decord from source and use it on the GPU.

**Comment by sanjayss34** [comment]
I've run into this issue as well (on cpu) -- does anyone have a fix?

**Comment by 2000ZRL** [comment]
I also met the same problem.

**Comment by Leo-yang-1020** [comment]
It stil exists now, not fixed. Hope to see more solutions

**Comment by btekin** [comment]
Setting `num_threads=1` in `VideoReader` resolves the issue for me.

**Comment by m4a1carbin4** [comment]
> Setting `num_threads=1` in `VideoReader` resolves the issue for me.

Thanks! it's work for me

**Comment by azuredsky** [comment]
does anyone solve it?

**Comment by suhyeok-jang** [comment]
> Setting `num_threads=1` in `VideoReader` resolves the issue for me.

Thanks!

**Comment by codyohl** [comment]
for this issue, I think the "fix" disables the automatic multithreading heuristics and setting a static number of threads - this fixes the reliability but can decimate the performance. the error code I see is -11, which seems like it would simply need a send/recv to flush buffers, do folks have ideas on this front
